[server]
enableCORS = false
enableXsrfProtection = false
headless = true
port = 8501

[theme]
base = "light"
primaryColor = "#8F5024"
backgroundColor = "#FAF8F5"
secondaryBackgroundColor = "#F0ECE6"
textColor = "#1F1A14"
font = "sans serif"
